// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iscfvetcindnqxfxeett.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzY2Z2ZXRjaW5kbnF4ZnhlZXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTkzODQsImV4cCI6MjA2MTk3NTM4NH0.fKvFr1a4xVGRWzX8FVSKCxMmNphD1J_K6mtiKH58dfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);